Create GDSC details Component
dsc-upt/gdsc-web-frontend pull request #27
Opened 2021-05-20 16:39 UTC by Nyubt

2021-05-20 16:50 UTC, Nyubt commented
![image](https://user-images.githubusercontent.com/12417376/119018075-5b272800-b9a4-11eb-9281-c1e7fa938ad2.png)
![image](https://user-images.githubusercontent.com/12417376/119018334-a5100e00-b9a4-11eb-9272-8b40f9f4ec05.png)
![image](https://user-images.githubusercontent.com/12417376/119018161-7a25ba00-b9a4-11eb-8aa6-fb32ae9fc84d.png)

2021-05-29 21:53 UTC, edi334 requested changes
The text and the image are too close to each other. Maybe add some padding

2021-05-29 21:53 UTC, edi334 commented on src/app/pages/home-page/components/gdsc-details/gdsc-details.component.css
> +  text-align: justify;
we can remove this because the text looks weird on smaller screens with only 2 words on some rows because of it

2021-06-05 21:03 UTC, MoNNsterFTW commented
![Screenshot_510](https://user-images.githubusercontent.com/26659303/120905413-bbee6b80-c606-11eb-8907-1f34e08468b2.png)
![Screenshot_511](https://user-images.githubusercontent.com/26659303/120905414-bc870200-c606-11eb-89c3-84021b732cf4.png)

2021-06-18 14:28 UTC, merged